#!/bin/sh
#
# install Apache HTTP server 
#

SOCKET_PREFIX="run/wsgi"

# STEP 1:  INSTALL RPMS

yum --assumeyes install httpd mod_wsgi


# STEP 2: FIREWALL SETUP 

# we enable access to port 80 from anywhere
# and make the iptables chages permanent 
if [ -z "`iptables -L | grep '^ACCEPT *tcp *-- *anywhere *anywhere *state *NEW *tcp *dpt:http'`" ] 
then 
    iptables -I INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT
    service iptables save
fi


# STEP 3: SETUP THE DEFAUT SITE 

#NOTE 1: Current setup does not support multiple virtual hosts. 
#NOTE 2: Current setup does not support HTTPS 

# check inf the <VirtualHost *:80> exists 
CONFS="/etc/httpd/conf/httpd.conf /etc/httpd/conf.d/*.conf"
CONF_DEFAULT="/etc/httpd/conf.d/00_default_site.conf"
CONF=

for F in $CONFS
do
    if [ 0 -lt `grep -c '^[ 	]*<VirtualHost[ 	]*\*:80>' $F` ]
    then
        CONF=$F
        break
    fi
done

#if the virtual host is not present - create one 

# number of EOxServer deamon processess 
EOXSNPROC=${EOXSNPROC:-8}

if [ -z "$CONF" ]
then
    CONF="$CONF_DEFAULT"
    echo "Default virtual host not located creting own one in: $CONF" 
    cat >"$CONF" <<END
# default site generated by the automatic EOxServer instance configuration 
<VirtualHost *:80>

    # WSGI process daemon used by EOxServer
    WSGIDaemonProcess eoxs_ows processes=$EOXSNPROC threads=1

</VirtualHost>
END
else
    echo "Default virtual host located in: $CONF" 
fi


# check whether WSGI socket is set already - if not do so 
CONF=

for F in $CONFS
do
    if [ 0 -lt `grep -c '^[ 	]*WSGISocketPrefix' $F` ]
    then
        CONF=$F
        break
    fi
done

if [ -z "$CONF" ] 
then # set socket prefix if not already set
    echo "WSGISocketPrefix is set to: $SOCKET_PREFIX"
    
    echo "WSGISocketPrefix $SOCKET_PREFIX" >> /etc/httpd/conf.d/wsgi.conf 
else 
    echo "WSGISocketPrefix set already:"
    grep -nH WSGISocketPrefix "$CONF"
fi

# STEP 4: START THE SERVICE  

# enable the HTTP service
chkconfig httpd on

# 
service httpd start



