#!/usr/bin/env bash
# 
#  DREAM AddProduct script template.
#  This script is invoked by the Ingestion Engine
#  during the addProduct operation on the interface
#   IF-DREAM-O-AddProduct
#
# usage:
# $0 [-replace=<existing_prod_id> | -add ] \
#    -dldir=<download_directory> \
#    -response=<filename>        \
#    -data=<datafile>            \
#    -meta=<metadatafile> 
#
# -replace / -add must occur first in the arg list.
# All files are relative to dldir, dldir is an absolute path.
#
# The response is a file to be generated by this script, and
#  must contain at least one of the following KV pairs:
#       productId=<eo-id>
#       url=<product-url>
#
# The response file is removed by the Ingestion Engine after
# processing it.
#
# The productId in the response file is the id of the newly
#  added product, the URL is where it can be accessed.
# The Ingestion Engine will read the response file once this
# script exits with a 0 status. An empty response file or no
# file is considered an error.
#
# A non-zero exit status indicates failure of the add product
# operation.
#

echo "Add Product script started on" $(date)
echo args: $*

if [[ $# < 5 ]]
then
    echo "Not enough args, exiting with status 5."
    exit 5
fi

if [[ $1 == '-add' ]]
then
    echo "action=add" 
elif [[ $1 == -replace=* ]]
then
    echo "action=replace"
    exProd=${1:9}
    echo "Existing Product Id: $exProd"
else
    echo '***bad action: ' $1
    echo "exiting with status 1"
    exit 1
fi

shift
for i in $*;
do
    case $i in
        -dldir=* | -response=* | -data=* | -meta=*) eval ${i:1};;
    esac
done


if [ -n  $response ] ; then

    response=$dldir/$response
    echo respfile $response

    if [[ -f $response ]] ; then
        echo $response "exists, exiting with status 3"
        exit 3
    fi

    echo "productId=eoid42" >$response

else
    echo "no respfile parameter, exiting with status 2".
    exit 2
fi

if [ -n  $data ] ; then
    data=$dldir/$data
    echo 'data:' $data
fi

if [ -n  $meta ] ; then
    meta=$dldir/$meta
    echo 'meta:' $meta
fi

if [[ ! -f $data ]] ; then
    echo "No data file: " $data
    echo echo "exiting with status 4"
    exit 4
fi

echo "test uqmd finishing with status 0."
exit 0
