#!/bin/bash
#
#  AddProduct action handler.
#
# USAGE:
#  product_add.sh [-replace=<existing_prod_id> | -add[=<collection>] ]
#    [-dldir=<download_directory>] -response=<filename>
#    -data=<datafile> [-meta=<metadatafile>][-catreg=<script>]
#
# PARAMETERS:
#
#   -add[=<collection>] Indicates that a new product shall be
#                       registered. Optionally, collection to
#                       which the product shall be inserted
#                       can be specified.
#   -replace=<prod_id>  Indicates the an existing product
#                       shall be replaced.
#   -id=<prod_id>       Product identifier to be used with the -add
#                       option.
#                       shall be replaced.
#   -dldir=<dir>        Download directory.
#   -response=<file>    File where the response should be written.
#   -data=<file>        Datafile to be registered.
#   -metadata=<file>    Product's meta-data.
#   -catreg=<script>    Optional catalogue registration script.
#
# DESCRIPTION:
#
# All files are relative to dldir, dldir is an absolute path.
#
# The response is a file to be generated by this script, and
#  must contain at least one of the following KV pairs:
#       productId=<eo-id>
#       url=<product-url>
#
# The response file is removed atomatically by the Ingestion
# Engine after processing it.
#
# The productId in the response file is the id of the newly
#  added product, the URL is where it can be accessed.
# The Ingestion Engine will read the response file once this
# script exits with a 0 status. An empty response file or no
# file is considered an error.
#
# A non-zero exit status indicates failure of the add product
# operation.
#

_set_eop_identifiers() {
  python <<END
import sys
from lxml import etree as et
xml = et.parse("$1",  et.XMLParser(remove_blank_text=True))
elm = xml.find("//{http://www.opengis.net/eop/2.0}EarthObservationMetaData/{http://www.opengis.net/eop/2.0}identifier")
if elm is not None:
    elm.text = "$2"
else:
    sys.exit(1)
elm = xml.find("//{http://www.opengis.net/eop/2.0}EarthObservationMetaData/{http://www.opengis.net/eop/2.0}parentIdentifier")
if elm is not None:
    elm.text = "$3"
with file("$1", "w") as fid:
    fid.write(et.tostring(xml, pretty_print=True, xml_declaration=True, encoding="utf-8"))
END
}

. "`dirname $0`/lib_common.sh"

info "Add product handler started ..."
info "PARAMS: $*"
#-----------------------------------------------------------------------------
# parse the CLI arguments
ACTION='ADD'
DIR="."

for _arg in $*
do
    _key="`expr "$_arg" : '\([^=]*\)'`"
    _val="`expr "$_arg" : '[^=]*=\(.*\)'`"

    case "$_key" in
        '-add' )
            ACTION="ADD" ; COLLECTION="$_val" ;;
        '-replace' )
            ACTION="REPLACE" ; IDENTIFIER="$_val" ;;
        '-id' )
            IDENTIFIER="$_val" ;;
        '-dldir' )
            DIR="$_val" ;;
        '-data' )
            DATA="$_val" ;;
        '-meta' | '-metadata' )
            META="$_val" ;;
        '-response' )
            RESPONSE="$_val" ;;
        '-catreg')
            CATREG="$_val" ;;
    esac
done

# check the CLI inputs
if [ -z "$ACTION" ] # no-action given error
then
    error "Missing mandatory '-add' or '--replace' action!" ; exit 1
fi

if [ "$ACTION" == "REPLACE" -a -z "$IDENTIFIER" ] # invalid replace action error
then
    error "REPLACE action requires an identifier!" ; exit 1
fi

if [ -n "$DIR" ]
then
    DIR="`_expand "$DIR"`"
fi

if [ -n "$DATA" ] # no-data given
then
    if [ -n "$DIR" -a "${DATA:0:1}" != '/' ]
    then
        DATA="`expr "$DIR" : '\(.*[^/]\)'`/$DATA"
    fi
    DATA="`_expand "$DATA"`"
else
    error "Missing mandatory data ('-data') specification!" ; exit 1
fi

if [ -n "$META" ] # no-metadata given
then
    if [ -n "$DIR" -a "${META:0:1}" != '/' ]
    then
        META="`expr "$DIR" : '\(.*[^/]\)'`/$META"
    fi
    META="`_expand "$META"`"
fi

if [ -n "$RESPONSE" ] # no-response given
then
    if [ -n "$DIR" -a "${RESPONSE:0:1}" != '/' ]
    then
        RESPONSE="`expr "$DIR" : '\(.*[^/]\)'`/$RESPONSE"
    fi
    RESPONSE="`_expand "$RESPONSE"`"
fi

#-----------------------------------------------------------------------------
# unpack zip archives
echo "DATA: $DATA"
echo "META: $META"
echo "DIR: $DIR"
echo "RESPONSE: $RESPONSE"

_unzip()
{
    info "Unpacking ZIP archive: $1 -> $2"
    if [ -f "$2" -o -d "$2" ]
    then
        rm -fvR "$2"
    fi
    mkdir "$2"
    unzip "$1" -d "$2"
}
_untargz()
{
    info "Unpacking TAR.GZ archive: $1 -> $2"
    if [ -f "$2" -o -d "$2" ]
    then
        rm -fvR "$2"
    fi
    mkdir "$2"
    tar -xvzf "$1" -C "$2"
}

_ungzip()
{
    info "Unpacking GZIP compressed file: $1 -> $2"
    if [ -f "$2" -o -d "$2" ]
    then
        rm -fvR "$2"
    fi
    gunzip -vc "$1" > "$2"
}

set -e
case "`file -b --mime-type "$DATA"`" in

    'application/x-gzip')
        if [ "`basename "$DATA"`" != "`basename "$DATA" '.tgz'`" -o "`basename "$DATA"`" != "`basename "$DATA" '.tar.gz'`" ]
        then
            DATA_SRC="$DATA"
            _untargz "$DATA" "$DATA.d"
            DATA="$DATA.d"
        elif [ "`basename "$DATA"`" != "`basename "$DATA" '.gz'`" ]
        then
            DATA_SRC="$DATA"
            _ungzip "$DATA" "${DATA%%.gz}"
            DATA="${DATA%%.gz}"
        fi
        ;;

    'application/zip')
        DATA_SRC="$DATA"
        _unzip "$DATA" "$DATA.d"
        DATA="$DATA.d"
        ;;
esac
set +e

#-----------------------------------------------------------------------------
# following command executes the format detection, data preparation,
# and metadata extraction
. "`dirname $0`/products.d/detect.sh"

# get collection ID
_EOP20="http://www.opengis.net/eop/2.0"
_xq="//{$_EOP20}EarthObservationMetaData/{$_EOP20}parentIdentifier/text()"
[ -z "$COLLECTION" ] && COLLECTION="`xml_extract.py "$IMG_META" "$_xq"`"
[ -z "$COLLECTION" ] && COLLECTION="`jq -r '.["name"]' "$IMG_RTYPE" `"
[ -z "$COLLECTION" ] && { error "Failed to determine the target collection identifier!" ; exit 1 ; }

# get dataset ID
_xq="//{$_EOP20}EarthObservationMetaData/{$_EOP20}identifier/text()"
[ -z "$IDENTIFIER" ] && IDENTIFIER="`xml_extract.py "$IMG_META" "$_xq"`"
[ -z "$IDENTIFIER" ] && { error "Failed to determine the target dataset identifier!" ; exit 1 ; }

# removing collons from the identifiers + assuring unique identifier
COLLECTION="`echo "$COLLECTION" | tr ':' '_'`"
IDENTIFIER="`echo "$IDENTIFIER" | tr ':' '_'`"

# collection prefix
[ -z "`echo "$IDENTIFIER" | grep "^$COLLECTION\."`" ] && IDENTIFIER="$COLLECTION.$IDENTIFIER"

# fixing the metadata
_set_eop_identifiers "$IMG_META" "$IDENTIFIER" "$COLLECTION"

info "ACTION=$ACTION"
info "COLLECTION=$COLLECTION"
info "IDENTIFIER=$IDENTIFIER"
info "DIR=$DIR"
info "DATA_SRC=$DATA_SRC"
info "DATA_LIST=$DATA_LIST"
info "VIEW_LIST=$VIEW_LIST"
info "DATA=$DATA"
info "META=$META"
info "RESPONSE=$RESPONSE"
info "IMG_DIR=$IMG_DIR"
info "IMG_DATA=$IMG_DATA"
info "IMG_VIEW=$IMG_VIEW"
info "IMG_VIEW_OVR=$IMG_VIEW_OVR"
info "IMG_VIEW_RTYPE=$IMG_VIEW_RTYPE"
info "IMG_META=$IMG_META"
info "IMG_RTYPE=$IMG_RTYPE"

#-----------------------------------------------------------------------------
# EOxServer registration
set -e

#create time-series
if $EOXS_MNG eoxs_id_check --type DatasetSeries "$COLLECTION"
then
    $EOXS_MNG eoxs_collection_create --type DatasetSeries -i "$COLLECTION"
    $EOXS_MNG eoxs_metadata_set -i "$COLLECTION" -s 'wms_view' -l "${COLLECTION}_view"
    $EOXS_MNG eoxc_layer_create -i "$COLLECTION" --time
fi

if $EOXS_MNG eoxs_id_check --type DatasetSeries "${COLLECTION}_view"
then
    $EOXS_MNG eoxs_collection_create --type DatasetSeries -i "${COLLECTION}_view"
    $EOXS_MNG eoxs_metadata_set -i "${COLLECTION}_view" -s 'wms_alias' -l "$COLLECTION"
fi

# load range-type
$EOXS_MNG eoxs_rangetype_load -i "$IMG_RTYPE"

# register the data and view
#TODO: fix coverage removal
$EOXS_MNG eoxs_id_check --type Coverage "$IDENTIFIER" || $EOXS_MNG eoxs_dataset_deregister "$IDENTIFIER"
$EOXS_MNG eoxs_id_check --type Coverage "${IDENTIFIER}_view" || $EOXS_MNG eoxs_dataset_deregister "${IDENTIFIER}_view"
$EOXS_MNG eoxs_dataset_register -r "`jq -r .name "$IMG_RTYPE"`" \
    -d "$IMG_DATA"  -m "$IMG_META" --collection "$COLLECTION" \
    --view "${IDENTIFIER}_view" $IMG_REG_OPT
$EOXS_MNG eoxs_dataset_register -r "$IMG_VIEW_RTYPE" -i "${IDENTIFIER}_view" \
    -d "$IMG_VIEW" -m "$IMG_META" --collection "${COLLECTION}_view" \
    --alias "$COLLECTION"

# id2path file registry
{
    echo "#$IDENTIFIER"
    $EOXS_MNG eoxs_i2p_list -f -i "$IDENTIFIER" | grep -v -e directory -e '^#' | sed -ne 's/^\([^;]*\);.*/\1;file/p'
    [ -n "$DATA_SRC" ] && echo "$DATA_SRC;file;source-data"
    [ -n "$IMG_DIR" ] && echo "$IMG_DIR;directory"
    [ -n "$META" -a "$META" != "$IMG_META" ] && echo "$META;metadata;$METADATA_FORMAT"
    echo "$IMG_META;metadata;EOP2.0"
    echo "$IMG_DATA;data"
    echo "$IMG_RTYPE;file;range-type"
    if [ -f "$DATA_LIST" ]
    then
        DATA_LIST_DIR="`dirname "$DATA_LIST"`"
        echo "$DATA_LIST;file"
        cat "$DATA_LIST" | while read F0
        do
            F="`_expand "$F0" "$DATA_LIST_DIR"`"
            [ -f "$F" ] && echo "$F;file"
            [ -d "$F" ] && echo "$F;directory"
        done
    fi
    echo "#${IDENTIFIER}_view"
    $EOXS_MNG eoxs_i2p_list -f -i "${IDENTIFIER}_view" | grep -v -e directory -e '^#' | sed -ne 's/^\([^;]*\);.*/\1;file/p'
    [ -n "$DATA_SRC" ] && echo "$DATA_SRC;file;source-data"
    [ -n "$IMG_DIR" ] && echo "$IMG_DIR;directory"
    echo "$IMG_META;metadata;EOP2.0"
    echo "$IMG_VIEW;data;browse"
    [ "$IMG_VIEW_OVR" ] && echo "$IMG_VIEW_OVR;file;overviews"
    if [ -f "$VIEW_LIST" ]
    then
        VIEW_LIST_DIR="`dirname "$VIEW_LIST"`"
        echo "$VIEW_LIST;file"
        cat "$VIEW_LIST" | while read F0
        do
            F="`_expand "$F0" "$VIEW_LIST_DIR"`"
            [ -f "$F" ] && echo "$F;file"
            [ -d "$F" ] && echo "$F;directory"
        done
    fi
} | $EOXS_MNG eoxs_i2p_load

#-----------------------------------------------------------------------------
# optional catalogue registration using on the fly generated manifest
# TODO: filling the other metadata

if [ -n "$CATREG" ]
then
{
cat - <<END
IDENTIFIER="$IDENTIFIER"
DATA="$IMG_DATA"
VIEW="$IMG_VIEW"
VIEW_OVR="$IMG_VIEW_OVR"
RANGE_TYPE="$IMG_RTYPE"
METADATA_EOP20="$IMG_META"
END
[ -n "$IMG_DIR" ] && echo "DOWNLOAD_DIR=\"$IMG_DIR\""
} | { "$CATREG" - || exit 1 ; }
fi

#-----------------------------------------------------------------------------
# generate the reponse file

if [ -n "$RESPONSE" ]
then
    info "Generating response file $RESPONSE"
    echo "productId=$IDENTIFIER" > "$RESPONSE"
    cat "$RESPONSE" | info_pipe
fi

#-----------------------------------------------------------------------------
info "Add product handler finished sucessfully."
